provides whole package lifecycle

diff --git a/src/deb/control/postrm b/src/deb/control/postrm
--- a/src/deb/control/postrm
+++ b/src/deb/control/postrm
@@ -1,2 +1,23 @@
 #!/bin/sh
 echo "POSTRM"
+set -e
+case "$1" in
+    abort-install)
+			echo "Abort installation";
+    ;;
+		remove)
+			echo "Remove";
+		;;
+		purge)
+			echo "Purge";
+		;;
+		upgrade)
+			echo "Upgrade";
+		;;
+		abort-upgrade)
+			echo "Abort upgrade";
+		;;
+		failed-upgrade)
+			echo "Failed upgrade";
+		;;
+esac
diff --git a/src/deb/control/prerm b/src/deb/control/prerm
--- a/src/deb/control/prerm
+++ b/src/deb/control/prerm
@@ -1,4 +1,20 @@
 #!/bin/sh
+
 SEMAGROW_SHORT_NAME="${distribution.all.package.shortname}";
-echo "removing semagrow init script"
-rm -f /etc/init.d/$SEMAGROW_SHORT_NAME
+
+echo "PREREMOVE"
+
+#rm -f /etc/init.d/$SEMAGROW_SHORT_NAME
+
+set -e
+case "$1" in
+    remove)
+	    echo "Remove";
+    ;;
+    upgrade)
+	    echo "Upgrade";
+    ;;
+    fail-upgrade)
+	    echo "Fail upgrade";
+    ;;
+esac
